# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  merge_request:
  branches: [master]
  workflow_dispatch:
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        run: npm i && npm run test
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    env: 
      HEROKU_API_KEY: ${secrets.bd924489-70ad-4af5-9547-71d04917e387}
    run: heroku container:login 
  - name: Build and push
    env:
      HEROKU_API_KEY: ${secrets.bd924489-70ad-4af5-9547-71d04917e387}
    run: heroku container:push -a episodesearch web 
  - name: Release
    env:
      HEROKU_API_KEY: ${secrets.bd924489-70ad-4af5-9547-71d04917e387}
    run: heroku container:release -a episodesearch web 
