# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test

name: pr-workflow

on:
# [to be filled]
jobs:
  test:
    runs-on: # [to be filled]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        # [rest to be filled]
